### ISSUE TITLE
Nooby Practices

### ISSUE THREAD

**Issue by Eruptsy** [UmRange/Console-DDOS-Tool#1]
Why isnt there a loop for the CLI. This is a half ass CLI that only ask you for input once :|. For that you could of just used the executed program’s command arguments 

https://github.com/UmRange/Console-DDOS-Tool/blob/1246ae10b3399a4a96dcc999817b8800d0e7ab33/Console-DDOS-Tool/Program.cs#L28

**Comment by UmRange** [comment]
This is for educational purposes only not for malicious use.
